openapi: "3.1.0"
info:
  title: My API
  version: "1.0.0"

paths:
  /responses:
    post:
      summary: Generate a response
      description: Tell a three sentence bedtime story about a unicorn.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                model:
                  type: string
                input:
                  type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
      # 添加 x-codeSamples 扩展
      x-codeSamples:
        - lang: bash
          label: "cURL (official style)"
          source: |
            curl https://api.openai.com/v1/responses \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $OPENAI_API_KEY" \
              -d '{
                "model": "gpt-4.1",
                "input": "Tell me a three sentence bedtime story about a unicorn."
              }'
