{
  "paths": {
    "/responses": {
      "post": {
        "summary": "Create a response",
        "operationId": "createResponse",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "model": {
                    "type": "string",
                    "example": "gpt-4.1"
                  },
                  "input": {
                    "type": "string",
                    "example": "Tell me a three sentence bedtime story about a unicorn."
                  }
                },
                "required": ["model", "input"]
              },
              "examples": {
                "curlExample": {
                  "summary": "Curl request",
                  "value": {
                    "curl": "curl --request POST \\\n  --url https://api.openai.com/v1/responses \\\n  --header 'Authorization: Bearer <token>' \\\n  --header 'Content-Type: application/json' \\\n  --data '{\n  \"model\": \"gpt-4.1\",\n  \"input\": \"Tell me a three sentence bedtime story about a unicorn.\"\n}'"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    }
  }
}
